### ISSUE TITLE
WP CLI cannot create local cache inside Docker Container

### ISSUE THREAD

**Issue by JodiWarren** [10up/wp-local-docker#107]
When running `./bin/setup.sh` the following error can be observed:
`Warning: Failed to create directory '/var/www/.wp-cli/cache/': mkdir(): Permission denied.`

This is because `/var/www` is owned by `root` and has `drwxr-xr-x` permissions, whereas WP CLI is being run as `www-data`

Off the top of my head, there are two solutions:
- We manually create `/var/www/.wp-cli/cache` and assign it to `www-data`
- This could be set to another directory via the `WP_CLI_CACHE_DIR` environment variable.

I'm no sysadmin though!

FWIW this doesn't seem to be actually causing any problems, this is entirely in service to making the error message go away.

**Comment by tlovett1** [comment]
@JodiWarren what operating system is this?

**Comment by pattonwebz** [comment]
This same thing happens for me on Ubuntu 18.04

**Comment by JodiWarren** [comment]
@tlovett1 I'm on MacOS 10.13.3, using Docker 18.03.1-ce-mac65.

**Comment by tlovett1** [comment]
@cmmarslender mind taking a look?

**Comment by cmmarslender** [comment]
This message has been showing up when using WP-CLI to install WP inside the containers for a while, but it shouldn't actually break anything. I believe the only impact is that we can't cache a copy of the archive of WordPress inside the container, but since its installed once, and then persisted to the filesystem outside of the container and the cache would be deleted once the container was turned off anyways, it was never high on the priority list to fix. 

I can look into fixing the message at some point, but it shouldn't be breaking anything in the meantime :)

**Comment by tlovett1** [comment]
@cmmarslender that would be great. Thanks

**Comment by cmmarslender** [comment]
This was fixed in https://github.com/10up/wp-local-docker-images/commit/348f9ef4d6df9a7dacb637026bfa6963dc105b92

You'll need to `docker pull 10up/phpfpm:latest` to get the latest image that has the directory present.

So far, 7.2/latest are done building, and the rest are in queue.
