### ISSUE TITLE
Remove `restart:always` from default configs

### ISSUE THREAD

**Issue by pattonwebz** [10up/wp-local-docker#116]
Having the services always restart results in a race condition after 2 separate instances of the docker `wp-local-docker` are used. On machine restart (or docker restart) each instance has containers wanting to bind to the same ports but only one can bind to the ports on the local host.

It's been mentioned in slack a few times that this has caused people some issues. Having containers only restart when manually started would solve this.

**Comment by colorful-tones** [comment]
I've had ongoing issues with ports clashing and have yet to be able to note the exact steps to replicate. For now the only solution I've found is having to restart my computer whenever I want to switch sites using WP Local Docker, which is kind of frustrating.

I'm going to experiment in coming days with removing the `restart:always` and I'll report back on if it helps my situation.

**Comment by christianc1** [comment]
The behavior described here should not be present if containers are removed.

`docker-composer down`
or
`docker stop $(docker ps -aq) && docker rm $(docker ps -aq)`

**Comment by moraleida** [comment]
Noting here that the default policy for `restart` is no: https://docs.docker.com/compose/compose-file/#restart. 

It seems to be aimed at keeping containers live in case of software/hardware failures. I can't really make sense of it for development work but I might be missing something.

**Comment by pattonwebz** [comment]
@christianc1 Using `docker-compose down` will remove volumes defined in the file as well - which might not be expected behaviour for since generally volumes are defined for data persistence between container stop/starts. In most cases you would want the database to remain between uses if your working on the same project for more than one task.

EDIT: correction the volumes would be fine with a `down` because the data volumes are host mounted directories :)

**Comment by christianc1** [comment]
@pattonwebz Volumes meant to persist are mounted from the host.  Containers can be safely removed.  The database is mounted from `<project-root>/data/db`, and the codebase is mounted from `<project-root>/wordpress`.  Configuration files are also mounted see `<project-root>/config`.

**Comment by pattonwebz** [comment]
@christianc1 yup, my bad I already noticed my mistake and was editing my other comment I guess at same time as you were writing your :stuck_out_tongue:

**Comment by colorful-tones** [comment]
~~Ok, it is a new dawn and a new day. Here are steps to recreating the issue I keep encountering and pretty much making me give up on using WP Local Docker.~~

~~Note: I have Docker set as a startup item, and MAMP Pro is not a startup item _at all_. Nor, any MySQL instances that I'm aware of.~~

1.  ~~Restart MacBook Pro~~
2. ~~Open iTerm and run `docker ps` ([screenshot #1 of output](https://www.dropbox.com/s/7idolct4ttna3uw/Screenshot%202018-08-15%2009.10.43.png?dl=0))~~
3. ~~Run `docker stop $(docker ps -aq) && docker rm $(docker ps -aq)` ([screenshot #2 of output](https://www.dropbox.com/s/l9kgw5vs3fpxt83/Screenshot%202018-08-15%2009.10.58.png?dl=0))~~
4. ~~I opened both of my site's `docker-compose.yml` for clientx and clienty in VS Code and removed all instances of `restart:always`, save and close.~~
5. ~~Run `docker ps` again for safe measure ([screenshot #3 of output](https://www.dropbox.com/s/y81zw40ca0np10u/Screenshot%202018-08-15%2009.11.06.png?dl=0))~~
6. ~~`cd` into clientx and run `dc up -d`, which is an alias for `docker-compose up -d` ([screenshot #4 of output](https://www.dropbox.com/s/daq39zssg15ydto/Screenshot%202018-08-15%2009.11.20.png?dl=0))~~
7. ~~Visit clientx site and get "Error establishing database connection"~~
8. ~~Run `lsof -i:3306` ([screenshot #5 of output](https://www.dropbox.com/s/t2qaay9wtpu5lew/Screenshot%202018-08-15%2009.11.26.png?dl=0))~~
9. ~~Run `docker stop $(docker ps -aq) && docker rm $(docker ps -aq)` (screenshot #6 of output](https://www.dropbox.com/s/amwxjosvfuipjl8/Screenshot%202018-08-15%2009.12.03.png?dl=0))~~
10. ~~Run `docker ps` ([screenshot #7 of output](https://www.dropbox.com/s/q34rft3uprps3et/Screenshot%202018-08-15%2009.12.12.png?dl=0))~~
11. ~~`cd` to clienty and run `dc up -d` ([screenshot #7 of output](https://www.dropbox.com/s/tdu3cw1v8svqrlv/Screenshot%202018-08-15%2009.28.08.png?dl=0))~~
12. ~~Visit clienty in browser and get "Error Establishing a Database Connection" in clienty~~

Please disregard all that ☝🏻

It seems that my issue was not related to whether `restart:always` was enabled, and was due to the fact that I had Query Monitor plugin installed and was causing conflicts with database connection.
