### ISSUE TITLE
Setup prompts are lacking

### ISSUE THREAD

**Issue by tlovett1** [10up/wp-local-docker#121]
I just ran through the setup prompts and they are pretty lacking. The questions aren't really explained and don't have proper labels.

**Comment by moraleida** [comment]
We've recently moved to using the default prompts provided by WP-CLI in #109 . Not sure we can filter those out to improve the copy on each prompt, but maybe we can display a helper message before the prompts start?

**Comment by kopepasah** [comment]
Since we are talking about the setup process, there is a way we could combine the process into one file (along with all the other commands) and create a rich environment with fancy prompts and feedback. 

It does add one extra requirement, but I think we all could agree it is a requirement everyone using this tool should already have installed locally: [Node](https://nodejs.org/en/).

**Comment by cmmarslender** [comment]
@kopepasah This is something I'm working on this half

**Comment by kopepasah** [comment]
@cmmarslender is there a branch you are using? I would love to contribute or take over.

**Comment by cmmarslender** [comment]
its currently in another repo - Its more of a generator than an update to this repo, that will end up generating a docker-compose file similar to what we have here, but with a bit more flexibility with versions and such
