### ISSUE TITLE
Mysql not installing correctly

### ISSUE THREAD

**Issue by webdingens** [10up/wp-local-docker#133]
I'm on Windows 10 Professional 1803 using Hyper-V and Docker CE 18.06 from a Ubuntu WLS. Whenever I run docker-compose up for the first time MySQL stops the database initialization with:
`[ERROR] 29  File './sys/x@0024schema_flattened_keys.frm' not found (Errcode: 2 - No such file or directory)`

When I `docker-compose down / up` the container is started, but `bin/setup.sh` tells me IP xx.xx.xx.xx cannot connect on localhost. Upon logging into the mysql instance of the mysql container and running
`SELECT host, user FROM mysql.user;`
I get a
`ERROR 29 (HY000): File './mysql/user.MYD' not found (Errcode: 2 - No such file or directory)`

Is this a file system problem? Any ideas? I had problems with Symlinks before. :)

**Comment by derula** [comment]
I just had the same error in an entirely unrelated project, while also using MySQL over Docker on Windows. I'm not really sure what is wrong here. At first I suspected that the problem is due to the MySQL data being in "bind mount" volume (which on Windows is more of a network drive, courtesy of Hyper-V), but I think I had that same setup before and it worked fine. I'll update if I figure something out...

**Comment by beerwin** [comment]
Did you manage to figure something out? I have the same problem.

**Comment by derula** [comment]
wp-local-docker-v2 fixes this by using a named volume instead of a bind mount, this should work on Windows, too. Here is how you can do that, in docker-compose.yml:
```yml
version: '3'
services:
  mysql:
    image: mysql:5
    volumes:
      - "mysqlData:/var/lib/mysql"
# ...
volumes:
  mysqlData:
```
However, I'm not sure if this will cause problems, since then, the MySQL data files won't be available in the data/db folder anymore, so if any other part of wp-local-docker relies on them being there, it would be a problem. Otherwise you can probably try upgrading to wp-local-docker-v2.

**Comment by cmmarslender** [comment]
@derula suggestion should work fine. Nothing else is expecting them in the directory except for MySQL

**Comment by flavienbwk** [comment]
Not really a solution, sadly. A real solution must be brought by the Docker team !

**Comment by derula** [comment]
I have a feeling that as long as the Windows version of Docker is running inside a VM, there won't be a fantastic solution for this issue. File sharing between a virtualization host and guest just isn't great™.

**Comment by flavienbwk** [comment]
A great challenge for the developers. With significant stakes.
