### ISSUE TITLE
Access created .test domain through local network

### ISSUE THREAD

**Issue by jessemarco** [10up/wp-local-docker#139]
How to access created instance from any local network computer.

Thank you.

**Comment by cmmarslender** [comment]
This is a bit outside of what is officially supported for this project, but in theory it should work ok. The container will be listening on port 80 on whatever device WP Local Docker is running on so as long as you don't block this port to other computers with a firewall and the .test domain is pointing to the computer's IP Address (instead of 127.0.0.1) it should work.
