### ISSUE TITLE
Error: '/var/www/html/' is not writable by current user.

### ISSUE THREAD

**Issue by ghost** [10up/wp-local-docker#17]
Currently running a mostly fresh copy of the DigitalOcean Docker App.

After cloning this project into the home directory, running `docker-compose up -d` and following that with `sh bin/setup.sh`, I get the full error output:

`Error: '/var/www/html/' is not writable by current user.`
`Error: This does not seem to be a WordPress install.`
`Pass --path='path/to/wordpress' or run 'wp core download'.`

Running as sudo changes nothing. I've even killed all processed in Docker and re-downloaded the project but I get the exact same outcome.

These steps worked perfectly on my local copy on a Windows machine.

Any ideas?

**Comment by dustinrue** [comment]
I was able to replicate this using Docker 17.04 on 16.04 on digital ocean and I found this workaround:

```
chmod o+w wordpress
```

This will allow it to install wordpress. I can't speak to how well this will continue to work however. I'm also noticing that the ElasticPress container fails to work properly. Not sure what it is about this environment but it seems somewhat broken.

**Comment by thadroe** [comment]
Same issue here on Ubuntu 16.04 desktop.

`chmod o+w wordpress/` does work to run the script and get the wordpress files installed, but the subsequent problem is all files are owned by www-data with insufficient permissions to be writable by the local user.

I've had the same permissions issue with many other docker setups for wordpress. It seems to be linux specific. The only workaround I've been successful with so far has been to modify the builds to run the webserver and PHP with a username, UID, and GID that matches my local user.

I'd love to know of a better solution other than constantly changing permissions or modifying the builds in that way.

**Comment by dustinrue** [comment]
Strange because it works perfectly on OS X. You'd expect the opposite.

**Comment by thadroe** [comment]
Yeah no issues when I try on OSX either. I suspect OSX doesn't have the same issue because of the [osxfs file sharing system](https://docs.docker.com/docker-for-mac/osxfs/).

**Comment by bmakowski** [comment]
I have similar problem after running `sh bin/setup.sh`
```
Warning: cURL error 28: Resolving timed out after 10537 milliseconds
Error: cURL error 28: Resolving timed out after 10533 milliseconds
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

**Comment by moraleida** [comment]
`chmod o+w wordpress/` didn't work for me because every time a new file was created from the container it would get the old permissions and I'd have to repeat.

I had partial success using a modified version of `bin/setup.sh` like this:

```
#!/bin/bash

if [ -f "./wordpress/wp-config.php" ];
then
	echo "WordPress config file found."
else
	echo "WordPress config file not found. Installing..."
	docker-compose exec --user root phpfpm adduser $USER && usermod -aG www-data $USER
	docker-compose exec --user $USER phpfpm wp core download
	docker-compose exec --user $USER phpfpm wp core config --dbhost=mysql --dbname=wordpress --dbuser=root --dbpass=password
	docker-compose exec --user root phpfpm chown -R $USER:www-data .
fi
```

What it does is create the same username you're using as host inside the container, and add it to the `www-data` group. Then it runs the common tasks as the new user and in the end `chown`'s all files to be `$USER:www-data`. When the site runs as `www-data` if will have access to my files from the container because it's in the group, and I will as well, because the users match on the host.

So far this is working ok because I already had a `www-data` group on the host. Not extensively tested, but it's some progress at least.

--
edit: just realized you'd have to do this every time the container gets started. back to the drawing board.

**Comment by etherealite** [comment]
I found a similar solution to this issue, as officially documented by the [docker4wordpress](https://github.com/wodby/docker4wordpress/)  project. I'm thinking maybe their solution could be adapted to this project.

In docker4wordpress, they change permissions on the host to match those of the container -- see the[ relevant page](http://docs.docker4wordpress.org/en/latest/permissions/) in the docker4wordpress documentation. This is similar to the the solution proposed by @moraleida, but has more  of a fire and forget type of simplicity to it.

**Comment by moraleida** [comment]
Made some progress on this, though not enough for a pull-request yet - needs better automation. 

Current approach: 
1. Add a new file `bin/linux-info.sh`:
```
#!/bin/bash

echo "Your current user is $USER and your current user ID is $(id -u $USER)";
```

2. Add instructions to Dockerfile right before the `CMD` command:

```
# If you're on a linux host, open a terminal window and run
# $ bin/linux-info.sh
#
# Uncomment the line below and replace {USER_ID} and {USER_NAME} with the values returned
# RUN useradd -s /bin/bash -u {USER_ID} -G $(id -g www-data) {USER_NAME}

CMD ["php-fpm"]
```

This creates a user inside the container at the time of build (so it's permanent). It uses the same ID/name as the host and adds it to the `www-data` group. This is a first step. 

3. Modify  `bin/setup.sh` to run the commands as the new user/group:

```
#!/bin/bash

if [ -f "./wordpress/wp-config.php" ];
then
	echo "WordPress config file found."
else
	echo "WordPress config file not found. Installing..."
	docker-compose exec --user $USER:www-data phpfpm wp core download
	docker-compose exec --user $USER:www-data phpfpm wp core config --dbhost=mysql --dbname=wordpress --dbuser=root --dbpass=password
fi
```

This makes it so that the files downloaded are accessible by both the host and container. I'm not sure how portable this solution is (i.e if it runs on macs and windows ok). If it's not portable we can add a `setup-linux.sh` file with it.

4. Last step needed is changing my `dcwp` alias on `.bash_profile` to run as the new user:

`alias dcwp='docker-compose exec --user $USER:www-data phpfpm wp'   `

_et voilà_, I can now run wp-cli to install plugins/core and have the new files be accessible on host and container without constantly running `chmod` or `chown` to fix things.

**Comment by moraleida** [comment]
Just pushed a solution a bit more polished on #42 . Still need to fix the bash scripts to make use of the mapped users when on linux hosts. I've been running variations of this solution for the past couple of days without issue, making use of this alias:

`
alias dcwp='docker-compose exec --user $USER:www-data phpfpm wp'`

**Comment by moraleida** [comment]
I think I got a good/easy solution now. Appreciate any testing on #42. 

The only extra-step needed during a fresh install is running `bin/linux-setup.sh` before the first `docker-compose up`.

**Comment by zazazack** [comment]
👍 @dustinrue worked for me.

**Comment by apb1963** [comment]
If you put wp users in web server group, then wp users have access to web server files.  Unless you trust all of your wp users, that would be bad.  I believe that if you do in the other way (put web server user in wp group) and give the wp user ownership of the wp files, then you'll get the effect you're looking for without the security implications, afaik.

**Comment by cmmarslender** [comment]
Linux permission issues should be resolved with changes to the php and wpsnapshots images merged in https://github.com/10up/wp-local-docker-images/commit/d51e31d44f0cba0e525bad01b639a2b2c1faf27d
