### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by c9dd** [10up/wp-local-docker#29]
Hi,

Forgive the questions but I'm new to Docker and trying to learn new things. I'm getting 504 Gateway Time-out errors and I was wondering if that is due to the 'spec' of the setup? If so what recomendations would you give to help stop the error?

It happens just from time to time reloading pages.

**Comment by tlovett1** [comment]
You'll have to post your error logs

**Comment by c9dd** [comment]
Sure, where are they located?

**Comment by kopepasah** [comment]
@c9dd is this still an issue you are experiencing?

**Comment by c9dd** [comment]
@kopepasah Yep

**Comment by kopepasah** [comment]
Okay @c9dd.

If you could update us with steps to reproduce and log information, it would be very helpful to troubleshoot. Logs can be viewed while running after doing `docker-compose up` and any access or error logs from `nginx` will be found under `logs/nginx/`.

**Comment by xipasduarte** [comment]
Hello,

I'm having this issue too. It always takes a lot of time to load simple pages. I suspect that there is some weight coming from the site itself (it is a large multisite install), but there are some delays occurring on a clean install with the `setup.sh` script.

I leave the logs below for reference, but left out the nginx logs, because they contain standard request messages. Let me know if there is anything else that can help.

Thank you.

- **`error.log` entry**:
```
2018/10/08 17:10:07 [error] 6#6: *495 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET /fcg-agenda HTTP/1.1", upstream: "fastcgi://172.19.0.6:9000", host: "gulbenkian.test"
```


- **`docker-compose up` log**: https://www.dropbox.com/s/5ctb4pkqri3f484/docker-compose_up.log?dl=0

**Comment by jeffpaul** [comment]
@c9dd @xipasduarte note that we're archiving WP Local Docker in favor of the newer [WP Local Docker v2](https://github.com/10up/wp-local-docker-v2), so please update to the v2 version and we can discuss any further issues you see in its respective repo.  Thanks!
