### ISSUE TITLE
Why 'wordpress' as the directory name?

### ISSUE THREAD

**Issue by kopepasah** [10up/wp-local-docker#39]
I am just curious why `wp-local-docker` is using `wordpress` as the web root directory instead of something like `web`. The directory name, in this context, may seem a bit confusing because it is not necessarily where the installation of WordPress is located.

**Comment by emeaguiar** [comment]
Naming it `wordpress` is common practice for some people, I guess this was the case when this was originally written. 

Though I agree something line `public_html` or better yet, `htdocs` is more accurate. 

I'll try to get a pull request this weekend, though if you want to do it, you're welcome to.

**Comment by moraleida** [comment]
I like using `wordpress` for it, makes it clear that the folder is where the WordPress files are - not where they are served from. Inside the container the site actually served from `/var/www/html` which is standard so I don't see why this would be an issue.

Since Docker allows for a very flexible directory structure, many other folders could be at the same level, including different mount points for folders that in the container would be inside `/var/www/html`. Maybe using a generic name on the host folder might not be that accurate.

**Comment by tlovett1** [comment]
Yep, that's just what we named it :)

**Comment by kopepasah** [comment]
Thanks for chiming in everyone! It was primarily out of curiosity.
