### ISSUE TITLE
New variable for password resulting in no password displayed at the end of the installation

### ISSUE THREAD

**Issue by benoitchantre** [10up/wp-local-docker#88]
In #87, a prompt has been added to ask for the admin password with a new variable name. At the end of the script, the password is no more displayed (it was previously a random generated password).

https://github.com/10up/wp-local-docker/blob/46e50ce72170c1d27e302fc68fefaf5bf5f12e18/bin/setup.sh#L47-L51

https://github.com/10up/wp-local-docker/blob/46e50ce72170c1d27e302fc68fefaf5bf5f12e18/bin/setup.sh#L53-L58

https://github.com/10up/wp-local-docker/blob/46e50ce72170c1d27e302fc68fefaf5bf5f12e18/bin/setup.sh#L115-L119

If there's a preference to prompt for a password rather than displaying a random password at the end of the installation, it is probably no worth to display the credentials at the end of the script.

My suggestion is to keep the previous variable name, more in line with [WP-CLI options names](https://developer.wordpress.org/cli/commands/core/install/) and to remove the display of the credentials at the end of the script.

**Comment by simondowdles** [comment]
@benoitchantre Thanks for raising this. I submitted the PR that added the prompt, and I see @cmmarslender recently commented in that merge stating that the username and password are displayed at the end.

In all honesty, I did not see that password output at the end, HOWEVER, due to the fact that the browser was opened automatically the moment the script was finished executing, I imagine a lot of people will carry the same confusion.

My suggestion is to simply alter the post script output to show the password the user selected, in case they forgot, and just for consistency sake.

@cmmarslender @tlovett1 any preferences?
